apiVersion: v1
kind: Secret
metadata:
  name: cosmos-secrets
type: Opaque
stringData:
  COSMOS_ENDPOINT: "https://rudrapriyan.documents.azure.com:443/"
  COSMOS_KEY: "Zb9QbS6onpJuo6KaymTOLohEs4hzP43zwls2Jzvt8KUtonBlB8i8CtGwzgrmd2gU10fqdoPCEl0PACDbJdWnNg=="
  COSMOS_DATABASE_ID: "StudentAchievementsDB"
  COSMOS_CONTAINER_ID: "Achievements"
  ADMIN_USERNAME: "220701232@rajalakshmi.edu.in"
  ADMIN_PASSWORD: "Rudrapriyan@1"
  JWT_SECRET: "Malinovsky@BCD2024"
